### ISSUE TITLE
is it scaleable and ready for production

### ISSUE THREAD

**Issue by HamidReazaNikoonia** [kanzitelli/expo-rnn-starter#7]
is it scaleable and ready for production starter and are you recomment for use this boilerplate in high performance scaleable application in production ?

**Comment by kanzitelli** [comment]
@HamidReazaNikoonia hey! Well, this boilerplate is actually built based on the app I am working on at the moment as my side project and the app has a 10k daily users and the number is growing. So quick answer is yes. Of course, the app now has more folders like `services`, `utils`, etc. but this can be handled individually. Still I would like to add `wix-notifications`and `codepush` to this boilerplate so it would be more ready for production. During this week planning to upgrade to `react-native` 0.62. And also one todo in my list is to build an app, for example, news reader, that will be using this boilerplate and show how it reduces the time from `create-app` to `production` 🙂

**Comment by joonhocho** [comment]
@kanzitelli  could you share your app?

**Comment by kanzitelli** [comment]
@joonhocho I am not done with it yet but hopefully will finish during next two weeks and will share it for sure. If you wish, I can share a video of how it works now 🙂

**Comment by dpchami** [comment]
Any update with the app video @kanzitelli

**Comment by kanzitelli** [comment]
@dpchami hey! sorry for the late reply. Well, how you might have guessed, it didn't work how I have been expecting from my previous comment. So now I am transferring one of the app using this starter (v2.0) with new RN and RNN versions. And once I am done (should be during next 2 weeks), I will publish the video. Sorry for any inconveniences :)

**Comment by kanzitelli** [comment]
I am closing this issue due to me publishing the app for iOS -- https://apps.apple.com/ru/app/pyos-for-vk-%D0%BD%D0%B5%D0%B2%D0%B8%D0%B4%D0%B8%D0%BC%D0%BA%D0%B0-%D0%B4%D0%BB%D1%8F-%D0%B2%D0%BA/id819406913. It is an alternative client for VK, social network that is very famous in Russia, so it was huge work. And yes, answer to the initial question is yes, it's ready for production 🙂
